#!/bin/bash
ln -s /sd/modules/APITokens /pineapple/modules/APITokens
ln -s /sd/modules/autossh /pineapple/modules/autossh
ln -s /sd/modules/base64encdec /pineapple/modules/base64encdec
ln -s /sd/modules/Cabinet /pineapple/modules/Cabinet
ln -s /sd/modules/Collector /pineapple/modules/Collector
ln -s /sd/modules/Commander /pineapple/modules/Commander
ln -s /sd/modules/ConnectedClients /pineapple/modules/ConnectedClients
ln -s /sd/modules/CursedScreech /pineapple/modules/CursedScreech
ln -s /sd/modules/Deauth /pineapple/modules/Deauth
ln -s /sd/modules/DNSMasqSpoof /pineapple/modules/DNSMasqSpoof
ln -s /sd/modules/DNSspoof /pineapple/modules/DNSspoof
ln -s /sd/modules/dump1090 /pineapple/modules/dump1090
ln -s /sd/modules/DWall /pineapple/modules/DWall
ln -s /sd/modules/ettercap /pineapple/modules/ettercap
ln -s /sd/modules/EvilPortal /pineapple/modules/EvilPortal
ln -s /sd/modules/get /pineapple/modules/get
ln -s /sd/modules/HackRF /pineapple/modules/HackRF
ln -s /sd/modules/HTTPProxy /pineapple/modules/HTTPProxy
ln -s /sd/modules/KeyManager /pineapple/modules/KeyManager
ln -s /sd/modules/LEDController /pineapple/modules/LEDController
ln -s /sd/modules/Locate /pineapple/modules/Locate
ln -s /sd/modules/LogManager /pineapple/modules/LogManager
ln -s /sd/modules/MACInfo /pineapple/modules/MACInfo
ln -s /sd/modules/Meterpreter /pineapple/modules/Meterpreter
ln -s /sd/modules/ModemManager /pineapple/modules/ModemManager
ln -s /sd/modules/ModuleMaker /pineapple/modules/ModuleMaker
ln -s /sd/modules/ngrep /pineapple/modules/ngrep
ln -s /sd/modules/nmap /pineapple/modules/nmap
ln -s /sd/modules/Occupineapple /pineapple/modules/Occupineapple
ln -s /sd/modules/OnlineHashCrack /pineapple/modules/OnlineHashCrack
ln -s /sd/modules/OpenVPNConnect /pineapple/modules/OpenVPNConnect
ln -s /sd/modules/p0f /pineapple/modules/p0f
ln -s /sd/modules/Papers /pineapple/modules/Papers
ln -s /sd/modules/PortalAuth /pineapple/modules/PortalAuth
ln -s /sd/modules/RandomRoll /pineapple/modules/RandomRoll
ln -s /sd/modules/Responder /pineapple/modules/Responder
ln -s /sd/modules/SignalStrength /pineapple/modules/SignalStrength
ln -s /sd/modules/SiteSurvey /pineapple/modules/SiteSurvey
ln -s /sd/modules/SSLsplit /pineapple/modules/SSLsplit
ln -s /sd/modules/Status /pineapple/modules/Status
ln -s /sd/modules/tcpdump /pineapple/modules/tcpdump
ln -s /sd/modules/Themes /pineapple/modules/Themes
ln -s /sd/modules/tor /pineapple/modules/tor
ln -s /sd/modules/urlsnarf /pineapple/modules/urlsnarf
ln -s /sd/modules/wps /pineapple/modules/wps

